pipeline:
#  restore-cache:
#    image: drillster/drone-volume-cache
#    restore: true
#    mount:
#      - ./../bundler
#    volumes:
#      - /tmp/cache:/cache
#
#  run_tests:
#    image: ruby:2.5.3
#    environment:
#      RAILS_ENV: test
#    secrets: [ codecov_token ]
#    commands:
#      - gem update bundler
#      - bundle install --path=../bundler --jobs=5 --retry=3
#      - bundle exec rake db:create
#      - bundle exec rake db:migrate
#      - bundle exec rspec
#
#  rebuild-cache:
#    image: drillster/drone-volume-cache
#    rebuild: true
#    mount:
#      - ./../bundler
#    volumes:
#      - /tmp/cache:/cache

  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_id ]
    debug: true
    message: >
      {{#success build.status}}
        ✅ Success
      {{else}}
        ⛔️ Fail
      {{/success}}

      {{build.event}} by @{{commit.author}} to {{commit.branch}}

      {{{commit.message}}} / {{truncate commit.sha 8}}

      {{build.link}}/5

services:
  db:
    image: postgres:11
