inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.5.3

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
