version: "3"

services:
  app:
    container_name: daily-app
    image: registry.rezerbit.com/daily/develop/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    working_dir: /app
    command: /bin/sh -c "while true; do sleep 30; done"
    volumes:
      - ..:/app
      - bundle_cache:/bundle
    depends_on:
      - db
      - redis

  web:
    container_name: daily-web
    image: registry.rezerbit.com/daily/develop/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    working_dir: /app
    environment:
      # Need for not require bootsnap that has bug by debbuging. https://github.com/ruby-debug/ruby-debug-ide/issues/146
      # DEBUG_MODE: true
      WEBPACKER_DEV_SERVER_HOST: webpack_dev_server
    # Command for remote debug:
    # command: 'bash -c "rm -f /var/run/rails.pid && debug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -b 0.0.0.0 -p 80 --pid /var/run/rails.pid"'
    command: 'bash -c "rm -f /var/run/rails.pid && bin/rails s -b 0.0.0.0 -p 80 --pid /var/run/rails.pid"'
    volumes:
      - ..:/app
      - bundle_cache:/bundle
    ports:
      - 80:80
      # Port for remote debugger
      # - 1234:1234
    depends_on:
      - db
      - redis
      - app

  webpack_dev_server:
    container_name: daily-webpack_dev_server
    image: registry.rezerbit.com/daily/develop/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    working_dir: /app
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: 'bash -c "rm -rf /app/public/packs; bin/webpack-dev-server"'
    volumes:
      - ..:/app
      - bundle_cache:/bundle
    ports:
      - 3035:3035
    depends_on:
      - db
      - app

  db:
    container_name: daily-db
    image: postgres:11
    environment:
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    container_name: daily-redis
    image: redis:4
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  bundle_cache:
  pg-data:
  redis-data:
